### ISSUE TITLE
Create an initial release.

### ISSUE THREAD

**Issue by nathan-at-least** [ploteria/ploteria#12]
Hi, I found this repository via searching on crates.io under the `plotting` keyword, following the one with max recent downloads [criterion-plot](https://crates.io/crates/criterion-plot), then followed [the discussion](https://users.rust-lang.org/t/call-for-maintainers-criterion-plot/24413) to arrive here.

I'd like to play with this code as an unstable dependency, but there are no releases on crates.io. Can we make that happen? How can I help?

**Comment by Darksonn** [comment]
The project was pretty much abandoned back in February, so there are currently no plans to add a release on crates.io. If you still want to use it, you can use a git or local path dependency.

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

If you like the project, feel free to fork it and do some work on it. I'll probably be willing to take it up again if you do so, but I wont work on it alone.

**Comment by mfep** [comment]
@nathan-at-least, if it is still relevant, you can find the crate at https://crates.io/crates/ploteria. Thank you for your comment, and we are still looking forward to your feedback and/or contribution!

**Comment by Dylan-DPC** [comment]
Someone wishes to make the releases on places liek reddit & u.r.l.o?

**Comment by mfep** [comment]
What does `u.r.l.o` stand for? 🤨
I think we should mention the release in the [original forum thread](https://users.rust-lang.org/t/call-for-maintainers-criterion-plot/24413) as well as on reddit. 👍

**Comment by Dylan-DPC** [comment]
ah my bad :D 

i meant the users discourse forum
