### ISSUE TITLE
Build fails with toolchain version 1.44.0

### ISSUE THREAD

**Issue by mfep** [ploteria/ploteria#13]
The package fails to build with the currently latest tool-chain (1.44.0) because of language feature deprecation.

Reproduction:
```
> git clone https://github.com/ploteria/ploteria.git
> cd ploteria
> cargo build

...

   Compiling ploteria v0.1.0 (D:\Dev\ploteria)
error: trait objects without an explicit `dyn` are deprecated
   --> src\lib.rs:845:32
    |
845 |     fn cause(&self) -> Option<&::std::error::Error> {
    |                                ^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn (::std::error::Error)`
    |
note: the lint level is defined here
   --> src\lib.rs:390:9
    |
390 | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(bare_trait_objects)]` implied by `#[deny(warnings)]`

error: aborting due to previous error

error: could not compile `ploteria`.
```

**Comment by Dylan-DPC** [comment]
while at this, let's also remove the deny-warnings lint since any deprecation ro warning in the feature is going to break the build

**Comment by mfep** [comment]
> 
> 
> while at this, let's also remove the deny-warnings lint since any deprecation ro warning in the feature is going to break the build

I suggest not to remove that directive to maintain a better quality of the code-base. Language feature deprecation should not happen that often, and when it happens, it is for a reason.
