### ISSUE TITLE
replace set with concrete methods 

### ISSUE THREAD

**Issue by Dylan-DPC** [ploteria/ploteria#2]
In my opinion we should consider removing the `Set` trait and replacing the implementations with concrete methods. To see why I propose this, consider the following snippet from an example of the doc:

```rust
lp.set(Color::DarkViolet)
  .set(Label("sin(x)"))
  .set(LineType::Dash)
  .set(PointSize(1.5))
  .set(PointType::Circle)
```

While this code looks nice and readable, I want to propose changing the library to this:

```rust
lp.set_color(Color::DarkViolet)
  .set_label("sin(x)")
  .set_line_type(LineType::Dash)
  .set_point_size(1.5)
  .set_point_type(PointType::Circle)
```

The readability of the code is about the same, but it vastly improves the readability of the documentation for these setters, which currently looks like this:

![Screenshot from Figure](https://user-images.githubusercontent.com/928074/51704384-395a4800-2019-11e9-9c76-e06cb6f44b6f.png)

As you can see all setters on the `Figure` type are hidden in the traits section, which is both quite unusual and also has the problem that you need to scroll pretty far down to find them, and you also have to manually open the `impl` section of every setter to see its documentation:

![Screenshot from Figure](https://user-images.githubusercontent.com/928074/51704502-85a58800-2019-11e9-87fa-8bd4d0eac807.png)

Finally we get to remove the `proxy` module as well as a bunch of the types in the "Values used for settings" category above.

_Originally posted by @Darksonn in https://github.com/ploteria/ploteria/issues/1#issuecomment-457947438_

**Comment by peng1999** [comment]
Maybe it's better to drop the redundant "set", like this:
```
lp.color(Color::DarkViolet)
  .label("sin(x)")
  .line_type(LineType::Dash)
  .point_size(1.5)
  .point_type(PointType::Circle)
```

**Comment by Dylan-DPC** [comment]
@peng1999 Yes, i agree with it. It is also something the rust api guidelines put forth.
